### ISSUE TITLE
add plex autoscan to Community UI

### ISSUE THREAD

**Issue by mondychan** [PTS-Team/PTS-Team#27]
hello, just had an idea, would it be possible to add the output of "/opt/plex_autoscan/plex_autoscan.log" to the Community UI similar to rClone Logs ?

i know MrDoob is off to vacation without internet access, so wanted to post it here, so it wont get lots in the discord chat 

thx

**Comment by Hawkinzzz** [comment]
I believe MrDoob is already wanting to do this but needs a web developer to actually impliment it.

**Comment by MrDoobPG** [comment]
https://github.com/PTS-Team/PTS-Team/commit/a5d2049c9b6df0b55180acb1c71e4b93f4857a04#r36624074

sudo cp -rv /opt/plexguide/menu/pgui/templates/test-index.php /opt/appdata/pgui/index.php

**Comment by Hawkinzzz** [comment]
do a ptsupdate first, reinstall pgui from the core apps and then do the command MrDoob said above.

you should now see a window for the PAS logs

**Comment by MrDoobPG** [comment]
```
sudo ptsupdate && sudo ansible-playbook /opt/plexguide/menu/pgui/pgui.yml && sudo cp -rv /opt/plexguide/menu/pgui/templates/test-index.php /opt/appdata/pgui/index.php && sudo docker restart pgui
```

**Comment by MrDoobPG** [comment]
https://github.com/PTS-Team/PTS-Team/commit/38e721ba7f7d8218f687b9c2aada07ba737c9c6f
